theme = "hugo-theme-learn"
languageCode = "en-us"
title = "superluminar - Go Serverless Workshop"

[params]
editURL = "https://github.com/superluminar-io/godays-workshop/edit/master/website/content/"
themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-link'></i> Additional material"
url = "/links"
weight = 5

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
url = "https://github.com/superluminar-io/godays-workshop"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-question-circle'></i> Serverless docs"
url = "https://serverless.com/framework/docs/providers/aws/"
weight = 20

[[menu.shortcuts]]
name = "<i class='far fa-copyright'></i> Impressum"
url = "/impressum"
weight = 30
